let shopData = [
	{   
	    Serial: 1,
		id: "sdsdsd",
		src: 'images/img-1.jpg',
		name:'Casual Shirts',
		description:'Relaxed style for everyday comfort',
		price:'45',},
	{   
	    Serial: 2,
		id: 'dsdfdf',
		src: 'images/img-2.jpg',
		name:'Office Shirts',
		description:'Sophisticated office shirts for professional elegance.',
		price:'100',},
	{   
	    Serial: 3,
		id: 'sdsds',
		src: 'images/img-3.jpg',
		name:'T Shirts',
		description:'Casual comfort in trendy T-shirts.',
		price:'25',},
	{   
	    Serial: 4,
		id: 'dssdsdsdf',
		src: 'images/img-4.jpg',
		name:'Mens Suit',
		description:'Elegant mens suits for timeless sophistication.',
		price:'300',},
	{   
	    Serial: 5,
		id: 'sdsddfdfdff',
		src: 'images/product_img.jpg',
		name:'Head Set',
		description:'Immersive sound, sleek mobile headsets for on-the-go convenience.',
		price:'120',},
	{   
	    Serial: 6,
		id: 'sdsdgtghgdff',
		src: 'images/product1-1.jpg',
		name:'Hand Warmer',
		description:'Instant warmer for winter days.',
		price:'20',},
	{   
	    Serial: 7,
		id: 'sdsdrtrghgdff',
		src: 'images/product1-2.jpg',
		name:'Dumbbell',
		description:'Versatile dumbbells for effective strength training workouts.',
		price:'60',},
	{   
	    Serial: 8,
		id: 'sdsdtrtghgdff',
		src: 'images/product1-3.jpg',
		name:'Snow Goggles',
		description:'Snow goggles for clear, stylish vision on the slopes.',
		price:'80',},
	{   
	    Serial: 9,
		id: 'ghgdff',
		src: 'images/product1-4.jpg',
		name:'Fire Blanket',
		description:'Compact fire blanket for emergency safety, always within reach.',
		price:'20',},
	{   
	    Serial: 10,
		id: 'srtghgdff',
		src: 'images/product1-5.jpg',
		name:'Portable juice cup',
		description:'Portable juice cup for refreshing hydration on the go',
		price:'40',},
	{   
	    Serial: 11,
		id: 'sdhdfddff',
		src: 'images/product1-6.jpg',
		name:'Protective Helmet',
		description:'Protective helmet for safety and style.',
		price:'90',},
	{   
	    Serial: 14,
		id: 'sdsdfrr',
		src: 'images/product1-9.jpg',
		name:'Water Bottle',
		description:'Hydrate on the go with a versatile water bottle.',
		price:'30',},
	{   
	    Serial: 16,
		id: 'sdsdreredff',
		src: 'images/product2-1.jpg',
		name:'Baby Upper',
		description:'Adorable baby upper for cozy comfort.',
		price:'25',},
	{   
	    Serial: 17,
		id: 'sdhgdff',
		src: 'images/product2-2.jpg',
		name:'Sunscreen Clothing',
		description:'Sunscreen clothing for UV protection and style.',
		price:'12',},

	{   
	    Serial: 18,
		id: 'sdsderehgdff',
		src: 'images/product2-5.jpg',
		name:'Mens Upper',
		description:'Instant warmth for winter days...',
		price:'35',},
	{   
	    Serial: 19,
		id: 'sdehgdff',
		src: 'images/product2-7.jpg',
		name:'Body Suit',
		description:'Cute and cozy full-body suit for babies',
		price:'120',},
	]